name: dbz

services:
  kafka-1:
    image: apache/kafka:${KAFKA_VERSION}
    hostname: kafka-1
    ports:
      - "19092:9092"
      - "19093:9093"
    environment:
      CLUSTER_ID: ZpuFk35cSeC2NSXP_uoW2A
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-1-data:/var/lib/kafka/data
  
  kafka-2:
    image: apache/kafka:${KAFKA_VERSION}
    hostname: kafka-2
    ports:
      - "29092:9092"
      - "29093:9093"
    environment:
      CLUSTER_ID: ZpuFk35cSeC2NSXP_uoW2A
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:909
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,CONTROLLER://kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-2-data:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:${KAFKA_VERSION}
    hostname: kafka-3
    ports:
      - "39092:9092"
      - "39093:9093"
    environment:
      CLUSTER_ID: ZpuFk35cSeC2NSXP_uoW2A
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:909
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,CONTROLLER://kafka-3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-3-data:/var/lib/kafka/data

  oracle21:
    image: oracle/database:${ORACLE_VERSION}
    ports:
      - "1521:1521"
    volumes:
      - ./oracle_scripts:/opt/oracle/scripts/setup
    environment:
      ORACLE_PWD: cybertec
      
  postgres18:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: debezium
      POSTGRES_PASSWORD: dbz
      POSTGRES_USER: dbzuser

  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    links:
      - kafka-1
      - kafka-2
      - kafka-3
      - oracle21
      - postgres18
    ports:
      - "8083:8083"
    volumes:
      - /home/ian/oracle/ojdbc17.jar:/kafka/libs/ojdbc17.jar
    environment:
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest  
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - connect  
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local  
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092  
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
      AUTH_TYPE: LOGIN_FORM  
      SPRING_SECURITY_USER_NAME: admin  
      SPRING_SECURITY_USER_PASSWORD: Admin@123

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

# Versions
# Kafka    = 4.3.1 
# Debezium = 3.7
# Oracle   = 21
# Postgres = 18

# KAFKA_VERSION=4.3.1 DEBEZIUM_VERSION=3.7 POSTGRES_VERSION=18 ORACLE_VERSION=21 docker compose up -d
# KAFKA_VERSION=4.3.1 DEBEZIUM_VERSION=3.7 POSTGRES_VERSION=18 ORACLE_VERSION=21 docker compose down -v
