ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/XE' scope=spfile;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE FORCE LOGGING;

CREATE USER c##dbzuser IDENTIFIED BY dbz DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS CONTAINER=ALL;

GRANT CREATE SESSION TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;

GRANT CREATE TABLE TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzuser CONTAINER=ALL;

GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;

GRANT SELECT ON V_$LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$MYSTAT TO c##dbzuser CONTAINER=ALL; 
GRANT SELECT ON V_$STATNAME TO c##dbzuser CONTAINER=ALL; 

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE c##dbzuser.football_league (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(50),
	       CONSTRAINT fl_pk PRIMARY KEY (id)
	     );

CREATE TABLE c##dbzuser.football_team (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(100),
	       league VARCHAR2(50),
	       ground VARCHAR2(50),
	       CONSTRAINT ft_pk PRIMARY KEY (id)
	     );
			   
CREATE TABLE c##dbzuser.football_player (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(100),
               team NUMBER,
	       CONSTRAINT fp_pk PRIMARY KEY (id)
	     );

INSERT INTO c##dbzuser.football_league VALUES (1, 'Premier League');
INSERT INTO c##dbzuser.football_league VALUES (2, 'Championship');
INSERT INTO c##dbzuser.football_league VALUES (3, 'League One');
INSERT INTO c##dbzuser.football_league VALUES (4, 'League Two');

INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Southampton', 2, 'Saint Marys');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Liverpool', 1, 'Anfield');	
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Arsenal', 1, 'Emirates');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Ipswich Town', 2, 'Portman Road');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Lincoln City', 3, 'LNER Stadium');

INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Gavin Bazunu', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Shea Charles', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Leo Scienza', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Cody Gakpo', 2);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Victor Gyokeres', 3);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Jaden Philogene', 4);

COMMIT;

ALTER SESSION SET CONTAINER=cdb$root;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
