ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/XE' scope=spfile;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE FORCE LOGGING;

CREATE USER c##dbzuser IDENTIFIED BY dbz DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS CONTAINER=ALL;

GRANT CREATE SESSION TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;

GRANT CREATE TABLE TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzuser CONTAINER=ALL;

GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;

GRANT SELECT ON V_$LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$MYSTAT TO c##dbzuser CONTAINER=ALL; 
GRANT SELECT ON V_$STATNAME TO c##dbzuser CONTAINER=ALL; 

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE OR REPLACE DIRECTORY img_dir as '/opt/oracle/images';
GRANT READ ON DIRECTORY img_dir to c##dbzuser;

CREATE TABLE c##dbzuser.football_league (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(50),
	       CONSTRAINT fl_pk PRIMARY KEY (id)
	     );

CREATE TABLE c##dbzuser.football_team (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(100),
	       league VARCHAR2(50),
	       ground VARCHAR2(50),
	       image BLOB,
	       CONSTRAINT ft_pk PRIMARY KEY (id)
	     );
			   
CREATE TABLE c##dbzuser.football_player (
               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(100),
               team NUMBER,
	       CONSTRAINT fp_pk PRIMARY KEY (id)
	     );

INSERT INTO c##dbzuser.football_league VALUES (1, 'Premier League');
INSERT INTO c##dbzuser.football_league VALUES (2, 'Championship');
INSERT INTO c##dbzuser.football_league VALUES (3, 'League One');
INSERT INTO c##dbzuser.football_league VALUES (4, 'League Two');

INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Southampton', 2, 'Saint Marys');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Liverpool', 1, 'Anfield');	
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Arsenal', 1, 'Emirates');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Ipswich Town', 2, 'Portman Road');
INSERT INTO c##dbzuser.football_team (name, league, ground) VALUES ('Lincoln City', 3, 'LNER Stadium');

INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Gavin Bazunu', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Shea Charles', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Leo Scienza', 1);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Cody Gakpo', 2);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Victor Gyokeres', 3);
INSERT INTO c##dbzuser.football_player (name, team) VALUES ('Jaden Philogene', 4);

DECLARE
    v_bfile       BFILE;
    v_blob        BLOB;
    v_amount      INTEGER;
    v_dest_offset INTEGER;
    v_src_offset  INTEGER;

    TYPE file_array IS VARRAY(5) OF VARCHAR2(100);
    v_files file_array := file_array('Southampton.jpg', 'Liverpool.jpeg', 'Arsenal.jpg', 'IpswichTown.jpg', 'LincolnCity.jpeg');

BEGIN
    FOR i IN 1..5 LOOP

        v_dest_offset := 1;
        v_src_offset  := 1;

        v_bfile := BFILENAME('IMG_DIR', v_files(i));

        UPDATE c##dbzuser.football_team SET image = EMPTY_BLOB()
        WHERE id = i
        RETURNING image INTO v_blob;

	v_amount := DBMS_LOB.GETLENGTH(v_bfile);

        DBMS_LOB.FILEOPEN(v_bfile, DBMS_LOB.FILE_READONLY);
        DBMS_LOB.LOADBLOBFROMFILE(
            dest_lob    => v_blob,
            src_bfile   => v_bfile,
            amount      => v_amount,
            dest_offset => v_dest_offset,
            src_offset  => v_src_offset
        );

        DBMS_LOB.FILECLOSE(v_bfile);

    END LOOP;
    COMMIT;
END;
/

COMMIT;

ALTER SESSION SET CONTAINER=cdb$root;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
